# Generated by Django 6.0.5 on 2026-05-27 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(choices=[('get_job', 'Get a Job'), ('get_clients', 'Get Clients'), ('build_brand', 'Build Personal Brand'), ('grow_business', 'Grow My Business')], max_length=30)),
                ('aggression', models.CharField(choices=[('conservative', 'Conservative (safe, slow)'), ('balanced', 'Balanced (recommended)'), ('aggressive', 'Aggressive (fast, higher risk)')], default='balanced', max_length=20)),
                ('target_industry', models.CharField(blank=True, max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('target_location', models.CharField(blank=True, max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('bio_summary', models.TextField(blank=True, help_text="User's background and experience")),
                ('credentials_secret_key', models.CharField(blank=True, help_text='PyRunner Secret key name storing LinkedIn credentials', max_length=100)),
                ('datastore_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error - Action Required')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=100)),
                ('linkedin_name', models.CharField(blank=True, max_length=200)),
                ('linkedin_headline', models.CharField(blank=True, max_length=300)),
                ('linkedin_url', models.URLField(blank=True)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('connections_count', models.IntegerField(default=0)),
                ('module_posting', models.BooleanField(default=True)),
                ('module_commenting', models.BooleanField(default=True)),
                ('module_connecting', models.BooleanField(default=True)),
                ('module_job_applying', models.BooleanField(default=False)),
                ('module_client_hunting', models.BooleanField(default=False)),
                ('max_connections_per_day', models.IntegerField(default=20)),
                ('max_comments_per_day', models.IntegerField(default=15)),
                ('max_applications_per_day', models.IntegerField(default=10)),
                ('brand_primary_color', models.CharField(default='#1B4F72', max_length=7)),
                ('brand_secondary_color', models.CharField(default='#F39C12', max_length=7)),
                ('brand_watermark_text', models.CharField(blank=True, max_length=50)),
                ('post_days', models.JSONField(default=list, help_text='Days to post [0-6] 0=Monday')),
                ('post_time', models.CharField(default='08:00', help_text='HH:MM', max_length=5)),
                ('posts_per_week', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'linkedin_profiles',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('profile_url', models.URLField(blank=True)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Why this person was identified as a potential client')),
                ('trigger_post', models.TextField(blank=True, help_text='Post/comment that triggered identification')),
                ('stage', models.CharField(choices=[('identified', 'Identified'), ('connection_sent', 'Connection Request Sent'), ('connected', 'Connected'), ('message_sent', 'Message Sent'), ('replied', 'They Replied'), ('meeting_booked', 'Meeting Booked'), ('converted', 'Converted to Client'), ('not_interested', 'Not Interested')], default='identified', max_length=30)),
                ('connection_message_used', models.TextField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='linkedin.linkedinprofile')),
            ],
            options={
                'db_table': 'linkedin_leads',
                'ordering': ['-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('job_url', models.URLField()),
                ('linkedin_job_id', models.CharField(blank=True, max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_description_snippet', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Application Viewed'), ('responded', 'Employer Responded'), ('rejected', 'Rejected'), ('interview', 'Interview Scheduled')], default='applied', max_length=20)),
                ('cover_letter_used', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='linkedin.linkedinprofile')),
            ],
            options={
                'db_table': 'linkedin_job_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('thought_leadership', 'Thought Leadership'), ('personal_story', 'Personal Story'), ('industry_insight', 'Industry Insight'), ('achievement', 'Achievement/Win'), ('tip_framework', 'Tip or Framework'), ('hot_take', 'Hot Take/Opinion'), ('case_study', 'Case Study')], max_length=30)),
                ('post_text', models.TextField()),
                ('hook', models.CharField(blank=True, help_text='First line of post (the hook)', max_length=300)),
                ('hashtags', models.TextField(blank=True, help_text='Space-separated hashtags')),
                ('image_format', models.CharField(choices=[('abstract_scene', 'Abstract Conceptual Scene'), ('bold_statement', 'Bold Typography Card'), ('before_after', 'Before & After Split'), ('infographic_art', 'Infographic Art Card'), ('symbolic_object', 'Symbolic Object')], max_length=30)),
                ('image_prompt_used', models.TextField(blank=True, help_text='DALL-E prompt that generated this image')),
                ('image_url', models.URLField(blank=True, help_text='DALL-E generated image URL')),
                ('image_local_path', models.CharField(blank=True, help_text='Local processed image path', max_length=500)),
                ('image_emotion', models.CharField(blank=True, max_length=100)),
                ('image_metaphor', models.CharField(blank=True, max_length=200)),
                ('image_color_palette', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved - Queued to Post'), ('posted', 'Posted to LinkedIn'), ('failed', 'Failed to Post'), ('rejected', 'Rejected by User')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=200)),
                ('failure_reason', models.TextField(blank=True)),
                ('impressions', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('gpt_model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('dalle_model_used', models.CharField(default='dall-e-3', max_length=50)),
                ('generation_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='linkedin.linkedinprofile')),
            ],
            options={
                'db_table': 'linkedin_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
