# Generated by Django 6.0.5 on 2026-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedpost',
            old_name='dalle_model_used',
            new_name='image_model_used',
        ),
        migrations.RenameField(
            model_name='generatedpost',
            old_name='gpt_model_used',
            new_name='text_model_used',
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='image_provider',
            field=models.CharField(default='openai', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='text_provider',
            field=models.CharField(default='openai', max_length=50),
        ),
    ]
